WebApp/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FicRecs.DatabaseLib;
using FicRecs.WebApp.Models;
using System.Threading;

namespace WebApp.Controllers
{
    public class StoryController : Controller
    {
        const int pageSize = 20;
        ThreadLocal<Random> random;

        private readonly FicRecsDbContext _context;

        public StoryController(FicRecsDbContext context)
        {
            Random rand = new Random();
            random = new ThreadLocal<Random>(() =>
            {
                lock(rand)
                {
                    return new Random(rand.Next());
                }
            });

            _context = context;
        }

        // GET: StoryDetails
        public async Task<IActionResult> Index(bool showDetailed = false, int page = 1)
        {
            var fics = _context.StoryDetails;

            var model = new StoryIndexViewModel
            {
                ShowDetailed = showDetailed,
                Fics = await fics.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync(),
                CurrentPage = page,
                TotalPages = await fics.CountAsync() / pageSize
            };
            return View(model);
        }

        public async Task<IActionResult> Similar(int storyId = -1, bool showDetailed = false, int page = 1)
        {
            if (!StoryDetailsExists(storyId))
            {
                return View("NotFound", storyId);
            }

            var selectedFic = _context.StoryDetails.Where(d => d.StoryId == storyId);
            var similarFics = _context.StoryMatrix
                                .Where(m => m.StoryA == storyId)
                                .OrderByDescending(m => m.Similarity)
                                .Join(_context.StoryDetails, m => m.StoryB, d => d.StoryId, (m, d) => d);

            var model = new StorySimilarViewModel
            {
                StoryId = storyId,
                ShowDetailed = showDetailed,
                SelectedFic = await selectedFic.SingleOrDefaultAsync(),
                SimilarFics = await similarFics.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync(),
                CurrentPage = page,
                TotalPages = await similarFics.CountAsync() / pageSize
            };
            return View(model);
        }

        public async Task<IActionResult> Random()
        {
            var storyId = _context.StoryDetails
                                .Skip(random.Value.Next(await _context.StoryDetails.CountAsync()))
                                .Select(s => s.StoryId)
                                .First();

            return RedirectToAction("Similar", new { storyId = storyId });
        }

        // GET: StoryDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var storyDetails = await _context.StoryDetails
                .FirstOrDefaultAsync(m => m.StoryId == id);
            if (storyDetails == null)
            {
                return NotFound();
            }

            return View(storyDetails);
        }

        private bool StoryDetailsExists(int id)
        {
            return _context.StoryDetails.Any(e => e.StoryId == id);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FicRecs</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FicRecs</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <!--<p>&copy; 2018 - FicRecs</p>-->
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_StoryBrowseSearchPartial.cshtml
<div class="row">
    <div class="col-md-3">
        <form asp-controller="Story" asp-action="Similar" method="GET">
            <div class="form-group">
                <div class="input-group">
                    <input class="form-control" type="text" name="storyId" placeholder="Story ID" />
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-primary">View</button>
                    </span>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-3">
        <a asp-area="" asp-controller="Story" asp-action="Index" class="btn btn-default" role="button">View full fic list</a>
    </div>
    <div class="col-md-3">
        <a asp-area="" asp-controller="Story" asp-action="Random" class="btn btn-default" role="button">Random</a>
    </div>
</div>